apiVersion: v1
kind: Pod
metadata:
  name: pi-dht11
  labels:
    app: pi-dht11
spec:
  containers:
  - name: node-dht
    image: khubo/pi-dht11
    ports:
      - containerPort: 3000
    volumeMounts:
      - mountPath: /dev/gpiomem
        name: dev-gpiomem
    securityContext:
      privileged: true 
  volumes:
    - name: dev-gpiomem
      hostPath:
          path: /dev/gpiomem
